# ============================================
# CONFIGURATION SERVEUR
# ============================================
server.port=8080
spring.application.name=ecommerce-backend

# ============================================
# CONFIGURATION BASE DE DONNÉES (PostgreSQL)
# ============================================
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_db
spring.datasource.username=postgres
spring.datasource.password=rahery
spring.datasource.driver-class-name=org.postgresql.Driver

# ============================================
# CONFIGURATION JPA / HIBERNATE
# ============================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# ============================================
# CONFIGURATION LOGGING
# ============================================
logging.level.org.springframework.web=DEBUG
logging.level.com.ecommerce.backend=DEBUG

# ============================================
app.base-url=http://localhost:8080
# ============================================
# CORS CONFIGURATION
# ============================================
# Sera configuré dans un fichier Java plus tard